### ISSUE TITLE
InventoryOpenEvent error

### ISSUE THREAD

**Issue by madtomic** [TfT-02/Soulbound#47]
[23:22:44 ERROR]: Could not pass event InventoryOpenEvent to Soulbound v1.1.10-SNAPSHOT-b84
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:725) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.EntityPlayer.openContainer(EntityPlayer.java:657) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.BlockChest.interact(SourceFile:243) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:391) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:666) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
Caused by: java.lang.NullPointerException
        at com.me.tft_02.soulbound.config.ItemsConfig.isActionItem(ItemsConfig.java:143) ~[?:?]
        at com.me.tft_02.soulbound.listeners.InventoryListener.onInventoryOpen(InventoryListener.java:136) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[paperspigot-1.7.10.jar:git-PaperSpigot-4b7fb38]
        ... 17 more

**Comment by madtomic** [comment]
Were you able to look at this error?
